version: '3.8'

services:
  app:
    build:
      context: .
    # For development/debugging, uncomment
    # the command and volumes sections below,
    # then (re)run: "docker-compose up -d"
    # command: ["serve", "--reload", "diazo.ini"]
    # volumes:
    #   - .:/var/local/theme
    restart: always
    environment:
      # - APP_PROXY_ADDR=https://upload.printservice.uni-muenchen.de/
      - APP_PROXY_ADDR=http://lmzvd06-eop01.srv.mwn.de/
        # - APP_PROXY_ADDR=http://host.docker.internal/
    ports:
     - 5000:5000

  frontend:
    image: nginx:mainline-alpine
    restart: always
    volumes:
      - ./nginx/templates:/etc/nginx/templates
      - ./nginx/certs/:/etc/nginx/certs
    environment:
      - NGINX_HOST=themetest.local
    ports:
      - 80:80
      - 443:443
