version: '3.8'

services:
  app:
    build:
      context: .
    # For development/debugging, uncomment
    # the command and volumes sections below,
    # then (re)run: "docker-compose up -d"
    # command: ["serve", "--reload", "diazo.ini"]
    # volumes:
    #   - .:/var/local/theme
    environment:
      - APP_PROXY_ADDR=https://upload.printservice.uni-muenchen.de/
    ports:
     - 5000:5000

  frontend:
    image: nginx:1.25-alpine
    volumes:
      - ./nginx/templates:/etc/nginx/templates
      - ./nginx/certs/:/etc/nginx/certs
    environment:
      - NGINX_HOST=themetest.local
    ports:
      - 18080:80
      - 18443:443
